spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace_db
    username: root
    password: manfredas123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  servlet:
    session:
      timeout: 60m
  error:
    include-stacktrace: never