spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace_db
    username: root
    password: 15647821Aa!*

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  error:
    include-stacktrace: never